const greaterAccraCities = [
  "Abeka-Lapaz",
  "Abelemkpe",
  "Ablekuma",
  "Abokobi",
  "Abossey Okai",
  "Accra",
  "Accra New Town",
  "Achimota",
  "Ada Foah",
  "Ada Kasseh",
  "Adabraka",
  "Adenta",
  "Adenta East",
  "Adjei Kojo",
  "Adjen Kotoku",
  "Airport City Accra",
  "Airport Residential Area",
  "Akweteyman",
  "Alajo",
  "Ngleshie Amanfro",
  "Amasaman",
  "Apenkwa",
  "Ashaiman",
  "Ashongman",
  "Asoprochona",
  "Awoshie",
  "Ayi Mensa",
  "Bansa",
  "Big Ada",
  "Bubuashi",
  "Bubuashie",
  "Bukom",
  "Cantonments, Accra",
  "Caprice, Ghana",
  "Chorkor",
  "Christian Village",
  "Dansoman",
  "Darkuman",
  "Dawhenya",
  "Dodowa",
  "Dome, Ghana",
  "Dzorwulu",
  "East Legon",
  "Eleme, Ghana",
  "Frafraha",
  "Gbawe",
  "Gbegbe",
  "Haatso",
  "Kaneshie",
  "Kisseman",
  "Kokomlemle",
  "Kokrobite",
  "Korle Gonno",
  "Kotobabi",
  "Kuntunse",
  "Kwabenya",
  "Kwashieman",
  "Labadi",
  "Labone, Accra",
  "Lapaz (Accra)",
  "Lartebiokorshie",
  "Lashibi",
  "Lebanon, Ashaiman",
  "Legon",
  "Maamobi",
  "Madina, Ghana",
  "Makola, Ghana",
  "Mallam, Ghana",
  "Mamprobi",
  "Mataheko",
  "Miotso",
  "Nii Boi Town",
  "Nima, Accra",
  "Nmai Dzorn",
  "North Industrial Area, Accra",
  "Nungua",
  "Odorkor",
  "Ogbodjo",
  "Old Ningo",
  "Oyarifa",
  "Pantang",
  "Pig Farm (Ghana)",
  "Pokuase, Ghana",
  "Prampram",
  "Sabon Zongo",
  "Sakaman",
  "Sakumono",
  "Santeo",
  "Sege (town)",
  "Shai Hills",
  "Shiashie",
  "Sowutuom",
  "Sugbaniate",
  "Swalaba",
  "Taifa, Accra",
  "Tema",
  "Tema Community 1",
  "Tema Community 4",
  "Tema Community 5",
  "Tema Manhean",
  "Tesano",
  "Teshie",
  "Teshie-Nungua",
  "Torkuase",
  "Tudu, Ghana",
  "Weija",
];

export default greaterAccraCities;