const drugs = [
  {
    id: "1",
    name: "Aspirin",
    brand: "Bayer",
    price: 5.99,
    category: "Pain Relief",
    storeId: 101,
    description: "Pain reliever and fever reducer.",
    stock: 150,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNtF-JKjYL2eaQQziSZrNSvfZDzV46OUA_Zw&s",
  },
  {
    id: "2",
    name: "Ibuprofen",
    brand: "Advil",
    price: 6.49,
    category: "Pain Relief",
    storeId: 102,
    description: "Nonsteroidal anti-inflammatory drug.",
    stock: 200,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSaNF1fVEcPkcdKpZUT3zuBnM6qQn1SWvrqYQiGkKHckDj72pVi4NHoDRlfYUXxC-lscrI&usqp=CAU",
  },
  {
    id: "3",
    name: "Paracetamol",
    brand: "Tylenol",
    price: 4.99,
    category: "Pain Relief",
    storeId: 103,
    description: "Analgesic and antipyretic.",
    stock: 250,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTnhejZ3bDBWoc24gkmJX5xIaU7gWtFu6D_VA&s",
  },
  {
    id: "4",
    name: "Amoxicillin",
    brand: "Amoxil",
    price: 8.99,
    category: "Antibiotic",
    storeId: 104,
    description: "Penicillin antibiotic.",
    stock: 100,
    imageUrl: "https://example.com/amoxicillin.jpg",
  },
  {
    id: "5",
    name: "Loratadine",
    brand: "Claritin",
    price: 12.49,
    category: "Antihistamine",
    storeId: 105,
    description: "Allergy relief medication.",
    stock: 180,
    imageUrl: "https://example.com/loratadine.jpg",
  },
  {
    id: "6",
    name: "Metformin",
    brand: "Glucophage",
    price: 9.99,
    category: "Antidiabetic",
    storeId: 106,
    description: "Type 2 diabetes medication.",
    stock: 120,
    imageUrl: "https://example.com/metformin.jpg",
  },
  {
    id: "7",
    name: "Simvastatin",
    brand: "Zocor",
    price: 7.49,
    category: "Cholesterol",
    storeId: 107,
    description: "Statin used to control cholesterol.",
    stock: 160,
    imageUrl: "https://example.com/simvastatin.jpg",
  },
  {
    id: "8",
    name: "Omeprazole",
    brand: "Prilosec",
    price: 11.99,
    category: "Digestive Health",
    storeId: 108,
    description: "Proton pump inhibitor.",
    stock: 140,
    imageUrl: "https://example.com/omeprazole.jpg",
  },
  {
    id: "9",
    name: "Furosemide",
    brand: "Lasix",
    price: 10.49,
    category: "Diuretic",
    storeId: 109,
    description: "Diuretic used to treat fluid build-up.",
    stock: 90,
    imageUrl: "https://example.com/furosemide.jpg",
  },
  {
    id: "10",
    name: "Ciprofloxacin",
    brand: "Cipro",
    price: 14.99,
    category: "Antibiotic",
    storeId: 110,
    description: "Antibiotic used to treat infections.",
    stock: 110,
    imageUrl: "https://example.com/ciprofloxacin.jpg",
  },
  {
    id: "11",
    name: "Losartan",
    brand: "Cozaar",
    price: 13.99,
    category: "Hypertension",
    storeId: 111,
    description: "Used to treat high blood pressure.",
    stock: 130,
    imageUrl: "https://example.com/losartan.jpg",
  },
  {
    id: "12",
    name: "Atorvastatin",
    brand: "Lipitor",
    price: 16.99,
    category: "Cholesterol",
    storeId: 112,
    description: "Statin used to lower cholesterol.",
    stock: 170,
    imageUrl: "https://example.com/atorvastatin.jpg",
  },
  {
    id: "13",
    name: "Gabapentin",
    brand: "Neurontin",
    price: 19.49,
    category: "Neuropathic Pain",
    storeId: 113,
    description: "Used to treat nerve pain.",
    stock: 210,
    imageUrl: "https://example.com/gabapentin.jpg",
  },
  {
    id: "14",
    name: "Azithromycin",
    brand: "Zithromax",
    price: 17.99,
    category: "Antibiotic",
    storeId: 114,
    description: "Antibiotic used to treat infections.",
    stock: 80,
    imageUrl: "https://example.com/azithromycin.jpg",
  },
  {
    id: "15",
    name: "Levothyroxine",
    brand: "Synthroid",
    price: 18.49,
    category: "Thyroid",
    storeId: 115,
    description: "Used to treat hypothyroidism.",
    stock: 150,
    imageUrl: "https://example.com/levothyroxine.jpg",
  },
  {
    id: "16",
    name: "Pantoprazole",
    brand: "Protonix",
    price: 15.49,
    category: "Digestive Health",
    storeId: 116,
    description: "Proton pump inhibitor.",
    stock: 160,
    imageUrl: "https://example.com/pantoprazole.jpg",
  },
  {
    id: "17",
    name: "Albuterol",
    brand: "Ventolin",
    price: 20.99,
    category: "Respiratory",
    storeId: 117,
    description: "Bronchodilator used for asthma.",
    stock: 110,
    imageUrl: "https://example.com/albuterol.jpg",
  },
  {
    id: "18",
    name: "Clonazepam",
    brand: "Klonopin",
    price: 22.49,
    category: "Anxiety",
    storeId: 118,
    description: "Used to treat anxiety and seizures.",
    stock: 100,
    imageUrl:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.nps.org.au%2Fconsumers%2Fwarfarin&psig=AOvVaw3IMN_2HZgdalzMAnDUm8-a&ust=1721384170245000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCNjx1ryusIcDFQAAAAAdAAAAABAE",
  },
  {
    id: "19",
    name: "Prednisone",
    brand: "Deltasone",
    price: 12.99,
    category: "Corticosteroid",
    storeId: 119,
    description: "Used to treat inflammation.",
    stock: 130,
    imageUrl:
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.nps.org.au%2Fconsumers%2Fwarfarin&psig=AOvVaw3IMN_2HZgdalzMAnDUm8-a&ust=1721384170245000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCNjx1ryusIcDFQAAAAAdAAAAABAE",
  },
  {
    id: "20",
    name: "Warfarin",
    brand: "Coumadin",
    price: 25.99,
    category: "Anticoagulant",
    storeId: 120,
    description: "Used to prevent blood clots.",
    stock: 90,
    imageUrl:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6kjP1ziiFs07ofuA407CQBuaDYUASIZANaA&s",
  },
];

export default drugs;